# -*- coding: utf-8 -*-
"""Copy of Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1De3RLO1jyfO9erldJ3yZSWsAmL7UOsXV
"""

# pandas -- > pandas is an open source  lib which is used for handle data manipulation
import pandas as pd

# data structure of pandas ::
# 1. series ---> it stores only values not column name and it is one-dimensional
# 2. dataframe -- > it store values with column name, and it is multi - dimensional

a = pd.Series([1,22,23,29,90])
a

type(a)

# dataframe

a = {
    'emp_id' : [1,2,3,4,5],
    'name' : ['sam','mam','rahul','sameri','saloni'],
    'department' : ['IT','SALES','MARKET','IT','IT'],
    'Salary' : [10000,12000,13000,15000,16000]

}

df = pd.DataFrame(a)
df

# export this data into csv
df.to_csv('emp_data.csv')

# export data into excel
df.to_excel('emp_data.xlsx')

# import the data

a = pd.read_csv('/content/emp_data.csv')
a

